### PR TITLE
added geary symlink

### PR DESCRIPTION
**Pull request by Eskander**
I added a symlink for [Geary](https://wiki.gnome.org/Apps/Geary), the mail app from GNOME

### CODE REVIEW

**Comment by snwh** [comment]
Geary a third-party application, won't be providing an icon for that in this theme.

**Comment by Eskander** [comment]
Geary was adopted by the GNOME project after Yorba dissolved, see https://gitlab.gnome.org/GNOME/geary

**Comment by snwh** [comment]
In the sense that GNOME hosts all the old Yorba project code, it's not a GNOME Core app and it still retains the Geary branding. It's effectively in maintenance mode.

elementary folks did fork both of Geary and Shotwell into Pantheon Mail and Photos, and those are doing fairly well.

**Comment by snwh** [comment]
The line I drew is for the Suru icons is at including icons for the [GNOME Core Apps](https://wiki.gnome.org/Design/Apps) (other [link](https://en.wikipedia.org/wiki/GNOME_Core_Applications)) and Geary just isn't one of those. Evolution just hasn't been renamed to "Mail" since the project pre-dates the Core apps initiative (same goes for Empathy not being renamed "Chat").

**Comment by Eskander** [comment]
Fair enough, I apologize for any inconvenience

**Comment by snwh** [comment]
@Skqnder no worries, no inconvenience :)

**Pull request closed without merging**
