### PR TITLE
Symlinks for rhythmbox and shotwell

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/snwh/suru-icon-theme/issues/62
Closes https://github.com/snwh/suru-icon-theme/issues/60

- uses symlink from gallery-app for shotwell
- uses symlink from music-app for rhythmbox

### CODE REVIEW

**Comment by snwh** [comment]
If you add these to the [symlinks list](https://github.com/snwh/suru-icon-theme/blob/master/src/symlinks/fullcolor/apps.list) that'd be great ;)

**Comment by Feichtmeier** [comment]
Ah, sorry @snwh - done now!

**Comment by eaglersdeveloper** [comment]
Aren't these third-party applications?

**Comment by Feichtmeier** [comment]
No not really. They are the core music and gallery aps of Ubuntu and Foss and gnome apps. We also discussed this in the issue already

**Comment by eaglersdeveloper** [comment]
Music and Gallery icons are already have symlinks and using to GNOME Music and GNOME Photos respectively.
What if a user has at once Rhythmbox and GNOME Music, Shotwell and GNOME Photos?

**Comment by Feichtmeier** [comment]
What if they even install more than two music apps with a generic icon? 

The problem is that it's pretty sure that they will be yet again (I don't like this neither) the default music and gallery applications in Ubuntu 18.10.
So we had two options:
- provide a symlink to generic icons
- provide a unique shotwell and rhythm box icon

But as far as I interpret @snwh 's answer correctly, he likes the symlinks. That's the reason for this PR...

**Comment by eaglersdeveloper** [comment]
What about this?

rect3951

And so with all third-party applications. But will be problems with a licenses.

**Comment by snwh** [comment]
I will not be overlaying the rhythmbox icon like that. If the symlink move is controversial, I will simply remove them from the theme and either draw dedicated icons for them or leave them to have their original icons.

**Comment by snwh** [comment]
@Feichtmeier I mean in future

**Pull request merged**
