### PR TITLE
Fixed Setting and Tweaks names

### PR DESCRIPTION
**Pull request by wandrewkeech**
#42 On baseplate layer changed the names for each app to reflect the Gnome desktop names for those apps in 18.04

### CODE REVIEW

**Comment by wandrewkeech** [comment]
I'll keep adding fixes, if this is the right approach, for other icons I come across since updating to 18.04 yesterday.

**Comment by snwh** [comment]
Actually most additional icon names can be updated via symlinks.

**Comment by wandrewkeech** [comment]
Yes, that's what I saw in the snap package, but didn't see any symlinks in the project. Is there any way I can help?

**Comment by snwh** [comment]
It's already done

**Pull request closed without merging**
