### PR TITLE
Import from suru

### PR DESCRIPTION
**Pull request by merlijn-sebrechts**

### CODE REVIEW

**Comment by snwh** [comment]
I was happy to add debian packaging but  there was a bunch of issues with this PR.

First, `debian/copyright` says the icon set is GPLv3, it is not. The GPL license only accounts for the source render, scripts, etc. The icons themselves, which are PNG assets, are CC-by-SA.

Also `debian/control` is not accurate in several places

- there are packaging dependencies missing,
- it omits the cursor theme package entirely
- the description is not accurate to the Suru project scope

This PR also overwrites the main readme.

I think it's best if I write the debian packaging. I written them for icon and cursor themes before, so it's no trouble.

---

Which, I went ahead and did: https://code.launchpad.net/~snwh/suru-icon-theme/+git/packaging

For neatness, the debian packaging is separate from the main source repo (I do this for my other theme projects as well).

I also created a [daily-builds recipe](https://code.launchpad.net/~snwh/+recipe/suru-icon-theme-daily) which uses an imported [lp:suru-icon-theme](https://code.launchpad.net/~snwh/suru-icon-theme/suru-icon-theme-git) which is this repo.

**Comment by snwh** [comment]
I'm just working out the kinks over on the launchpad side of things

**Comment by merlijn-sebrechts** [comment]
Thanks! This PR was actually a mistake, I was trying to merge into `ubuntu/suru-icon-theme` but something went wrong (again).

However, it's good to know these issues. I'll try to fix them asap.

**Comment by snwh** [comment]
@galgalesh nevermind me. ~I dunno what happened but my packaging is completely busted keeps giving me `permission denied`, I dunno if you're willing to take a look: https://git.launchpad.net/~snwh/suru-icon-theme/+git/packaging/tree/debian and see if any errors jump out at you~ figured it out

**Pull request closed without merging**
