### PR TITLE
replace Makefile with meson build system, fixes #7

### LINKED ISSUE #7: Better build system
I kinda think I need something a little better than just a Makefile, not my area though.

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
@snwh Let me know if there's anything that should be done before merging this :)

### CODE REVIEW

**Comment by snwh** [comment]
Does the post install need to be python?

**Comment by bilelmoussaoui** [comment]
It's easier to access the ENV variables with python ;) plus, python is pre-installed on almost every linux distro out there

**Comment by snwh** [comment]
Actually I'll merge it and fix/change any potential issues I have with it.

**Comment by bilelmoussaoui** [comment]
Let me know if there's anything else I can do. Keep up the great work!

**Comment by snwh** [comment]
@bil-elmoussaoui might need a post-remove script to get rid of the gtk-icon-cache and reset the icon theme to default.

**Comment by bilelmoussaoui** [comment]
Meson doesn't have the ability to add a post remove script as far as i know :/

**Comment by snwh** [comment]
@bil-elmoussaoui it'd be something like this in theory

```python
#!/usr/bin/env python3

from os import environ, path
from subprocess import call

if not environ.get('DESTDIR', ''):
    PREFIX = environ.get('MESON_INSTALL_PREFIX', '/usr/local')
    print('Removing leftovers...')
    call(['rm', '-r', path.join(PREFIX, 'share/icons/Suru')])
    print('Reseting icon theme to default...')
    call(['gsettings', 'reset', 'org.gnome.desktop.interface icon-theme')])
```

**Comment by snwh** [comment]
It'd have to remove the `/usr/share/icons/Suru/icon-theme.cache` and reset the icon theme back to default

**Comment by bilelmoussaoui** [comment]
Yeah, but how to ask meson to execute that after running ninja uninstall? This should be reported upstream (if it's possible to be implemented)
Otherwise, the user has to run the script by himself. 
The org.gnome.desktop.interface isn't available everywhere. Cinnamon, for example, doesn't use it

**Comment by snwh** [comment]
@bil-elmoussaoui good point about the reset, just the cache removal then

**Pull request merged**
